// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {good} from '../models';

export function Debug(arg1:Array<any>):Promise<void>;

export function GetAllBestProfit():Promise<Array<good.Profit>>;

export function GetAllGoods():Promise<Array<good.Good>>;

export function Greet(arg1:string):Promise<string>;

export function RunCrawl():Promise<void>;

export function SavePrice():Promise<void>;

export function SetGoodPrice(arg1:string,arg2:number):Promise<void>;
