// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Debug(arg1) {
  return window['go']['main']['App']['Debug'](arg1);
}

export function GetAllBestProfit() {
  return window['go']['main']['App']['GetAllBestProfit']();
}

export function GetAllGoods() {
  return window['go']['main']['App']['GetAllGoods']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RunCrawl() {
  return window['go']['main']['App']['RunCrawl']();
}

export function SavePrice() {
  return window['go']['main']['App']['SavePrice']();
}

export function SetGoodPrice(arg1, arg2) {
  return window['go']['main']['App']['SetGoodPrice'](arg1, arg2);
}
